### ISSUE TITLE
Changing a module with remapped specifier doesn't cause a snapshot rebuild

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_core#122]
Not sure if that's a problem in `deno` or `deno_core`, but when I was changing `ext/node/polyfills/async_hooks.ts` which maps to `node:async_hooks` the snapshot was not getting rebuilt. I have a hunch that we might be outputting a wrong value to `cargo:rerun-if-changed` directive.

@nayeemrmn would you be able to look into this?

**Comment by nayeemrmn** [comment]
I can't reproduce. You're not using `__runtime_js_sources` right?

**Comment by bartlomieju** [comment]
> I can't reproduce. You're not using `__runtime_js_sources` right?

Correct, I was debugging https://github.com/denoland/deno/pull/20077 before landing `__runtime_js_source` and any change to the `async_hooks.ts` and `cargo build` finished immediately with changes not being reflected.

**Comment by bartlomieju** [comment]
Looks like it was a fluke. Closing for now.
