### ISSUE TITLE
`op2` fast async ops

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_core#147]
Fast async ops scheduled the op future in a fast call. This is used a lot in ext/websocket when we don't want to spend time polling the future in a slow call. eg:

https://github.com/denoland/deno/blob/main/ext/websocket/lib.rs#L576-L580
```rust
#[op(fast)]
pub async fn op_ws_next_event(
  state: Rc<RefCell<OpState>>,
  rid: ResourceId,
) -> u16 {
```

I couldn't find a way to do this with #[op2]. We should add support for it

**Comment by mmastrac** [comment]
Definitely. This is currently unsupported -- it's not too hard but it requires a bit of work.

**Comment by mmastrac** [comment]
Implemented!
