### ISSUE TITLE
`op2` with `#[buffer]` attribute doesn't work in some cases

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_core#205]
Trying to rewrite:
```rust
#[op]
fn op_encoding_decode(
  state: &mut OpState,
  data: &[u8],
  rid: ResourceId,
  stream: bool,
) -> Result<U16String, AnyError> {
```
to:
```
#[op2]
#[serde]
fn op_encoding_decode(
  state: &mut OpState,
  #[buffer] data: &[u8],
  #[smi] rid: ResourceId,
  stream: bool,
) -> Result<U16String, AnyError> {
```

Raises `// TypeError: expected typed ArrayBufferView`.

Should I explicitly use `buf: v8::Local<v8::ArrayBufferView>` here?

**Comment by mmastrac** [comment]
To better support fast calls, we no longer allow passing both ArrayBuffer or a typed buffer to a single method, so we may need to bifurcate this op into one that takes a u8 slice and one that takes other types.

The fastcall is only available if the argument is specifically Uint8Array.

**Comment by mmastrac** [comment]
Fixed by various PRs that added `#[anybuffer]` and `#[arraybuffer]`
