### ISSUE TITLE
Remove `core.setBuildInfo` and `core.build`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_core#213]
They do nothing in the context of `core`, and are only used in CLI.

**Comment by bartlomieju** [comment]
We rely on this info in several extensions - it was moved to the `core` so that we can share this information between the extensions instead of forwarding it from every `ext/` that needs it. I think we should keep it.

**Comment by bartlomieju** [comment]
I'm gonna close this one - it's useful to have this info available in core.
