### ISSUE TITLE
docs rs for deno_core is down

### ISSUE THREAD

**Issue by cole-abbeduto-particle** [denoland/deno_core#262]
It's been down since I checked Friday evening, not sure how much longer before that. Not sure what change broke this or how it works, but I wanted to report this so people can get on top of it if nobody has noticed yet.

https://docs.rs/deno_core/0.221.0/deno_core/

**Comment by bartlomieju** [comment]
It appears the build did just fine: https://docs.rs/crate/deno_core/0.221.0/builds/930245. Not sure what's the problem here. I'll be cutting another release tonight.

**Comment by bartlomieju** [comment]
Looks like docs are working now: https://docs.rs/deno_core/latest/deno_core/.
