### ISSUE TITLE
How to represent undefined in Rust on op arg or return?

### ISSUE THREAD

**Issue by cole-abbeduto-particle** [denoland/deno_core#291]
Hello Deno folks!

We've been using deno_core for a while now at my company and I've gotten to a point where I think I have a decent understanding of most things and what is possible. I am by no means an expert, but I can get what I need to get done done.

However, I haven't figured out how to represent undefined in Rust. I'd like to be able to represent it different than null within an arg or as a return from an op function. Is this possible? What would that code look like?

**Comment by mmastrac** [comment]
We reserve `undefined` for promises that are pending right now, but you should be able to return a `v8::Local<v8::Value>` with the value `undefined` from a sync op if needed. Note that we don't support undefined in fast ops -- those are only null because of limitations in v8.

**Comment by cole-abbeduto-particle** [comment]
Thank you @mmastrac, I appreciate your help! Few questions on that

1. How would I construct undefined as a `v8::Local<v8::Value>`?
2. In an op function, I would love to be able to take in a `v8::Value` and convert that into a `Result<Option<serde_json::Value>, anyhow::Error>` where
valid json -> Ok(Some(serde_json::Value)) 
undefined -> Ok(None) 
invalid json/not undefined -> Err(msg)
3. Related to 2, I've seen how I can convert the v8::Value into a serde_json::Value using serde_v8::from_v8 and giving it a HandleScope from the runtime, but is it possible to do this within an op function directly or would I have to store the Local on the OpState and convert it once I have access to the runtime? 
4. Are you telling me there are no functions in deno and that it is not possible to return undefined (void) from rust?
5. Sorry if this is the wrong place to ask questions like these, is there a better place for these types of questions?

**Comment by mmastrac** [comment]
Discord is definitely the best place for questions like this... there's a few other who can help.

1. This should work -- you just need a `HandleScope` https://docs.rs/rusty_v8/latest/rusty_v8/fn.undefined.html
2/3. I'm not totally sure what you're looking for here, but look through the deno source for `#[serde]` -- we do stuff that sounds kind of what you want to do in a few places. The answer to your question somewhat depends on how fast you want the solution to be. If you aren't worried about speed, just use `#[serde]` annotations for everything.
4. We don't currently return undefined from anything that I'm aware of, but we do support returning locals.

The ops are a bit of dark magic that we need to document better, but the best way to get help is to put together a little example with everything you'd like to do and we can definitely help put the pieces together.

I'd highly recommend studying the various forms of ops in deno_core and deno as you'll see pretty much everything that these are capable of.

I will close this issue for now but hop on Discord and we can discuss more interactively!
