### ISSUE TITLE
Help needed with extension middlewares

### ISSUE THREAD

**Issue by JomerDev** [denoland/deno_core#315]
Hello,

I'd like some help on how to use the extension middlewares, more specifically the event loop middleware.
I'm trying to have one rust thread and one js thread, the rust thread should be able to raise events in js by sending a message through an unbounded queue. From my limited understanding the event loop middleware seems to be the right place to check the queue on the js thread and raise the event in js if necessary but I don't understand how to interact with js in the middleware function. Could I get some pointers? Is the event loop middleware even the right place for that?

Thank you!

**Comment by mmastrac** [comment]
The event loop middleware is generally for things that just can't work with ops and promises, which are the best way to do any of this stuff.

I would recommend that you create an async op that listens on an unbounded queue to transfer work to JS rather than trying to use the middleware.

**Comment by JomerDev** [comment]
Thank you for the information. After posting the issue I ran across the websocket implementation in deno which achieves pretty much what I want with ops and promises
