### ISSUE TITLE
Add ability to call function with args on `JsRuntime`

### ISSUE THREAD

**Issue by yorinasub17** [denoland/deno_core#338]
Hello!

I'm working on a tool that embeds Deno as a runtime (after following [this blog post](https://deno.com/blog/roll-your-own-javascript-runtime)). I'm working on a feature that allows users to pass context arguments to a function they are writing, and found that there isn't an easy way to call a function with args (unless I am missing something). Is there any interest in adding a `call_with_args_and_await` method to `JsRuntime` that is basically `call_and_await`, but takes args?

E.g., https://github.com/yorinasub17/deno_core/commit/1675219c0e04d0ba2310aa8554c14bc4ca2f6630 (which I am happy to open as a PR if it is of interest)

Thanks for reading and considering this!

**Comment by bartlomieju** [comment]
Hey, sounds like a good idea and a PR would be more than welcome!

**Comment by yorinasub17** [comment]
Great! Took a stab at this here: https://github.com/denoland/deno_core/pull/341
