### ISSUE TITLE
Question regarding leaking `ExternalReferences` when making `JsRuntime`

### ISSUE THREAD

**Issue by nyannyacha** [denoland/deno_core#386]
Hi!
I'm sorry if this was a stupid question.

While I investigating the runtime that was built on Deno code base (actually edge-runtime of supabase 😁), I observed a memory leak on `JsRuntime` (and precisely the part of leaking external references).

But I don't understand why `ExternalReferences` should be leaked on all paths.

https://github.com/denoland/deno_core/blob/a2838062a8f51926140a48a8aa926330c6f9070c/core/runtime/jsruntime.rs#L698-L700

I knew that ownership of external references must be maintained while creating a snapshot [1] [2].
But I never heard that restriction also applied when creating a normal isolate instance 🧐 

Is there some background that I didn't know about on this?

Before I submitted this issue, I made a [fork] that adjusts the leak behavior, and there were no leaks regarding external references as expected.

There's the same discussion about this on the Deno repository, but that was open for a long time and it seems no one has a clear answer. 🙄 (https://github.com/denoland/deno/issues/18414)

Any thoughts about this?

[1]: https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-isolate.h;l=265-270?q=createparams&ss=chromium%2Fchromium%2Fsrc
[2]: https://github.com/denoland/rusty_v8/blob/60e0859514f340f2fdce064612e5de18ec8cfc3e/tests/test_api.rs#L5483-L5487
[fork]: https://github.com/nyannyacha/deno_core/commit/fd51ad55de7f24ac450af31a429a9902e40ad4b1

**Comment by mmastrac** [comment]
I'm about to rework a lot of the runtime/realm setup code over the next few weeks, so I can take a look at this when I'm in there.

**Comment by bartlomieju** [comment]
I believe this is now fixed in https://github.com/denoland/deno_core/pull/509

**Comment by nyannyacha** [comment]
@bartlomieju 🙄 But... If I'm looking at it right…it looks like you leaked the lifetime again...? Isn't it?
Am I looking at it wrong? I'm confused 😵‍💫

https://github.com/denoland/deno_core/pull/499
https://github.com/denoland/deno_core/blob/main/core/runtime/bindings.rs#L92-L94
https://github.com/denoland/deno_core/blob/main/core/runtime/setup.rs#L115-L129
