### ISSUE TITLE
Asynchronous cannot obtain return value

### ISSUE THREAD

**Issue by huiali** [denoland/deno_core#388]
``` 
let script_with_params = "(async () => {12})()";
    // execute_script_static
    let result = runtime.execute_script_static("<user-script>", &script_with_params)?;
    // run_event_loop
    runtime.run_event_loop(PollEventLoopOptions::default()).await?;

    let scope = &mut runtime.handle_scope();
    let local = v8::Local::new(scope, result);
    // Deserialize a `v8` object into a Rust type using `serde_v8`,
    // in this case deserialize to a JSON `Value`.
    let deserialized_value =
        serde_v8::from_v8::<serde_json::Value>(scope, local);
    Ok(deserialized_value.unwrap().to_string())

```
```
result:    {}

```
Excuse me, how should I write it to correctly obtain the return value within asynchrony？

**Comment by bartlomieju** [comment]
`(async () => {return 12})()`

**Comment by huiali** [comment]
Hello,

Thank you for your prompt response. I tried your suggestion by modifying the JavaScript function to (async () => {return 12})(). However, I'm still encountering issues in retrieving the expected result in Rust. The returned value I'm getting is still {}.

Here's the modified JavaScript snippet I used:

```
deno_core::extension!(ext, ops = [op_query_database]);
let mut runtime = JsRuntime::new(RuntimeOptions {
    module_loader: Some(Rc::new(deno_core::FsModuleLoader)),
    extensions: vec![ext::init_ops()],
    ..Default::default()
});


> let script_with_params = "(async () => {return 12})()";

// execute_script_static
let result = runtime.execute_script_static("<user-script>", &script_with_params)?;
// run_event_loop
runtime.run_event_loop(PollEventLoopOptions::default()).await?;

let scope = &mut runtime.handle_scope();
let local = v8::Local::new(scope, result);
// Deserialize a `v8` object into a Rust type using `serde_v8`
let deserialized_value = serde_v8::from_v8::<serde_json::Value>(scope, local);
Ok(deserialized_value.unwrap().to_string())
```
Could you please provide further guidance on what might be going wrong or suggest any additional modifications I should make to correctly obtain the return value of the asynchronous function?

In addition to my previous message, I also attempted another approach in Rust, but I'm still not able to retrieve the expected result. Here's the relevant portion of the code I used:
```
deno_core::extension!(ext, ops = [op_query_database]);
let mut runtime = JsRuntime::new(RuntimeOptions {
    module_loader: Some(Rc::new(deno_core::FsModuleLoader)),
    extensions: vec![ext::init_ops()],
    ..Default::default()
});

let script_with_params = "(async () => {return 12})()";
// execute user script
let result = runtime.execute_script_static("<user-script>", &script_with_params)?;
// run event loop, wait for async operations to complete
runtime.run_event_loop(PollEventLoopOptions::default()).await?;
// create HandleScope
let scope = &mut runtime.handle_scope();
// use scope to get string
let rust_string = result.open(scope).to_rust_string_lossy(scope);
println!("rust_string:{:#?}", rust_string);
Ok(rust_string)
```
When I run this, the output doesn't reflect the expected result of 12, but rather I still receive an empty or incorrect result. I'm not sure if there's a problem with how I'm using deno_core or if there's a mistake in how I'm handling the async function in JavaScript.

Could you provide any insights or suggestions on what might be going wrong with this approach as well?

Thank you for your patience and help.

**Comment by bartlomieju** [comment]
Ah right, you have an async function - which means the return value is a `Promise`. You can use `JsRuntime::resolve()` function to wait for this promise to complete and then proceed to deserialize it:
```rust
deno_core::extension!(ext, ops = [op_query_database]);
let mut runtime = JsRuntime::new(RuntimeOptions {
    module_loader: Some(Rc::new(deno_core::FsModuleLoader)),
    extensions: vec![ext::init_ops()],
    ..Default::default()
});


> let script_with_params = "(async () => {return 12})()";

// execute_script_static
let result = runtime.execute_script_static("<user-script>", &script_with_params)?;
runtime.resolve(result).await?;

let scope = &mut runtime.handle_scope();
let local = v8::Local::new(scope, result);
// Deserialize a `v8` object into a Rust type using `serde_v8`
let deserialized_value = serde_v8::from_v8::<serde_json::Value>(scope, local);
Ok(deserialized_value.unwrap().to_string())
```

**Comment by huiali** [comment]
Hello again,

Thank you for your continued assistance. I have followed your suggestion to use JsRuntime::resolve(), but I'm encountering an issue where the script execution seems to hang indefinitely. Here's the relevant code snippet:
```
deno_core::extension!(ext, ops = [op_query_database]);
let mut runtime = JsRuntime::new(RuntimeOptions {
   extensions: vec![ext::init_ops()],
   ..Default::default()
});

let script_with_params = "(async () =>  12)();";
// 执行用户脚本
let result = runtime.execute_script_static("<user-script>", &script_with_params)?;
let res=runtime.resolve(result).await?;
let scope = &mut runtime.handle_scope();
let local = v8::Local::new(scope, result);
// Deserialize a `v8` object into a Rust type using `serde_v8`
let deserialized_value = serde_v8::from_v8::<serde_json::Value>(scope, local);
Ok(deserialized_value.unwrap().to_string())
```

When I use runtime.resolve(result).await?;, the execution doesn't seem to complete, leading to an infinite hang. This is different from my earlier approach where I used runtime.run_event_loop(). With run_event_loop(), the script executes, but I face difficulties in retrieving the result.

Could you please help me understand why runtime.resolve() is causing an indefinite hang in this case? Also, is there a difference in how runtime.run_event_loop() and runtime.resolve() handle script execution that might affect retrieving the result?

Any further insights or suggestions you could provide would be greatly appreciated.

Thank you.

**Comment by bartlomieju** [comment]
@mmastrac could. you take a look here? I'm confused as well, I thought that `JsRuntime::resolve` was meant to do exactly that - do we need to run `JsRuntime::run_event_loop()` concurrently to have it work correctly?

**Comment by mmastrac** [comment]
@bartlomieju @huiali  Correct, you need to run `JsRuntime::run_event_loop` concurrently or it won't resolve. I recommend using https://docs.rs/deno_core/latest/deno_core/struct.JsRuntime.html#method.with_event_loop_promise.

**Comment by bartlomieju** [comment]
That's fine, but then I think docstring on `JsRuntime::resolve` should hint that the event loop needs to be polled, from what it reads right now:
```
/// Waits for the given value to resolve while polling the event loop.
  ///
  /// This future resolves when either the value is resolved or the event loop runs to
  /// completion.
```
it hints that it automatically runs the event loop.

**Comment by mmastrac** [comment]
Looks like I need to fix that comment, it's definitely wrong

**Comment by bartlomieju** [comment]
> Looks like I need to fix that comment, it's definitely wrong

Thanks!

**Comment by huiali** [comment]
@mmastrac @bartlomieju 
Thank you for your response and the suggestion to use JsRuntime::with_event_loop_promise. I understand the need to run JsRuntime::run_event_loop concurrently for the script to resolve properly. However, I'm not entirely clear on how to implement this in my current setup.

Could you kindly provide a bit more guidance or a simple example on how to use JsRuntime::with_event_loop_promise in conjunction with JsRuntime::run_event_loop? An illustrative snippet showing the correct way to set this up would be immensely helpful.

Thank you once again for your patience and assistance.

**Comment by huiali** [comment]
```
deno_core::extension!(ext, ops = [op_query_database]);
let mut runtime = JsRuntime::new(RuntimeOptions {
extensions: vec![ext::init_ops()],
..Default::default()
});
let script_with_params = "(async () => { return 12 })()";
let result = runtime.execute_script_static("<user-script>", script_with_params);
let value = runtime.with_event_loop_promise(Box::pin(async move{ result }), PollEventLoopOptions::default()).await?;
let scope = &mut runtime.handle_scope();
let rust_string = value.open(scope).to_rust_string_lossy(scope);
Ok(rust_string)
```
return ``` [object Promise]```

**Comment by huiali** [comment]
Hello again,

I appreciate your guidance on using JsRuntime::with_event_loop_promise. I attempted to implement it based on your suggestion, but I'm still facing challenges in retrieving the return value from the executed script. Here is the code snippet I used:

```
#[op2(async)]
#[smi]
pub async fn op_async_add_smi(#[smi] x: u32, #[smi] y: u32) -> u32 {
    tokio::time::sleep(Duration::from_millis(10)).await;
    x + y
}

deno_core::extension!(ext, ops = [op_async_add_smi]);
let mut runtime = JsRuntime::new(RuntimeOptions {
    extensions: vec![ext::init_ops_and_esm()],
    ..Default::default()
});

let script_with_params = "const op_async_add_smi = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";
let result = runtime.execute_script_static("<user-script>", script_with_params);
let value = runtime.with_event_loop_promise(Box::pin(async move { result }), PollEventLoopOptions::default()).await?;
let scope = &mut runtime.handle_scope();
let rust_string = value.open(scope).to_rust_string_lossy(scope);
println!("rust_string:{:#?}", rust_string);
```
However, I am still not able to obtain the return value from the script. The script execution does not seem to yield the expected result, and I'm not sure what I might be missing or doing incorrectly.

Could you please help me understand what might be going wrong with this implementation? Any further insights or specific examples would be highly beneficial.

Thank you once again for your assistance.

**Comment by mmastrac** [comment]
I believe this is wrong:

> `let script_with_params = "const op_async_add_smi = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";`

It should be:

> `let script_with_params = "const { op_async_add_smi } = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";`

**Comment by huiali** [comment]
Hello,

Thank you for your prompt response and the correction regarding the script. I made the suggested change:
```
let script_with_params = "const { op_async_add_smi } = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";
```
However, I'm still encountering the same issue. The script execution continues to return "[object Promise]". This leads me to believe that the issue might be related to how the Promise's resolved value is being retrieved, rather than the script itself.

Here's the relevant part of my Rust code:
```
//... [Previous setup code]
let result = runtime.execute_script_static("<user-script>", script_with_params);
let value = runtime.with_event_loop_promise(Box::pin(async move { result }), PollEventLoopOptions::default()).await?;
let scope = &mut runtime.handle_scope();
let rust_string = value.open(scope).to_rust_string_lossy(scope);
println!("rust_string:{:#?}", rust_string);
```


从您的描述中看来，尽管您按照作者的建议进行了修改，但是您的脚本仍然返回 “[object Promise]”，这表明您获取的是一个未解析的 Promise 对象，而不是该 Promise 解析后的值。这确实表明问题可能出在如何正确处理这个 Promise 上，以获取其最终的返回值。以下是您可以用来回复作者的内容：

Hello,

Thank you for your prompt response and the correction regarding the script. I made the suggested change:

rust
Copy code
let script_with_params = "const { op_async_add_smi } = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";
However, I'm still encountering the same issue. The script execution continues to return "[object Promise]". This leads me to believe that the issue might be related to how the Promise's resolved value is being retrieved, rather than the script itself.

Here's the relevant part of my Rust code:

rust
Copy code
//... [Previous setup code]

let value = runtime.with_event_loop_promise(Box::pin(async move { result }), PollEventLoopOptions::default()).await?;
let scope = &mut runtime.handle_scope();
let rust_string = value.open(scope).to_rust_string_lossy(scope);
println!("rust_string:{:#?}", rust_string);
It appears that I'm not capturing the resolved value of the Promise correctly. Could you please provide some guidance on how to properly extract the final value from the Promise returned by the executed script? Any further insights or examples would be greatly appreciated.

Thank you once again for your help.

**Comment by huiali** [comment]
> Hello,
> 
> Thank you for your prompt response and the correction regarding the script. I made the suggested change:
> 
> ```
> let script_with_params = "const { op_async_add_smi } = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";
> ```
> 
> However, I'm still encountering the same issue. The script execution continues to return "[object Promise]". This leads me to believe that the issue might be related to how the Promise's resolved value is being retrieved, rather than the script itself.
> 
> Here's the relevant part of my Rust code:
> 
> ```
> //... [Previous setup code]
> let result = runtime.execute_script_static("<user-script>", script_with_params);
> let value = runtime.with_event_loop_promise(Box::pin(async move { result }), PollEventLoopOptions::default()).await?;
> let scope = &mut runtime.handle_scope();
> let rust_string = value.open(scope).to_rust_string_lossy(scope);
> println!("rust_string:{:#?}", rust_string);
> 
> // rust_string:"[object Promise]"
> ```
> 
> It appears that I'm not capturing the resolved value of the Promise correctly. Could you please provide some guidance on how to properly extract the final value from the Promise returned by the executed script? Any further insights or examples would be greatly appreciated.
> 
> Thank you once again for your help.

I believe the issue lies in the way I'm handling the promise resolution in Rust. I'm looking for a way to correctly retrieve the final resolved value of the asynchronous operation executed in the script. Are there any examples in the source code, perhaps unit tests, that demonstrate how to properly handle and retrieve the result of an asynchronous operation in this context?

**Comment by huiali** [comment]
Hello,

I wanted to update you on my progress. I have managed to successfully retrieve the return value from the asynchronous operation using a different approach in Rust. Here's the snippet of the solution I used:
```
// Creating a persistent handle_scope reference
let mut handle_scope = runtime1.handle_scope();
// Creating a HandleScope
let scope = &mut v8::HandleScope::new(&mut handle_scope);
// Creating a context
let context = v8::Context::new(scope);
let scope = &mut v8::ContextScope::new(scope, context);
let code = r#"
    (async() => await 2)();
"#;
let script = v8::String::new(scope, code).unwrap();
let script = v8::Script::compile(scope, script, None).unwrap();
let result = script.run(scope).unwrap();
let promise = v8::Local::<v8::Promise>::try_from(result)
    .expect("Expected a Promise");
assert!(promise.state() == v8::PromiseState::Fulfilled);
let result = promise.result(scope);
let result_string = result.to_string(scope).unwrap().to_rust_string_lossy(scope);
println!("Result: {}", result_string);

```
This approach involves creating a HandleScope and a context, then compiling and running the script within this context. The result is then obtained from the Promise. This method effectively addresses the issue I was encountering with the asynchronous operation return values.

Thank you once again for all your assistance.

**Comment by bartlomieju** [comment]
> `let script_with_params = "const { op_async_add_smi } = Deno.core.ensureFastOps();(async () =>  await op_async_add_smi(1,2) )()";`

I think this is not correct - this script has now two elements, none of them is returned from the evaluation. If you want to return the resulting promise of `op_async_add_smi` I would do something like this:
```rust
let script_with_params = "(async () => { const { op_async_add_smi } = Deno.core.ensureFastOps(); return await op_async_add_smi(1,2); )()";
```

**Comment by huiali** [comment]
Hello,

Thank you for your continued support. I wanted to update you on my progress and also seek your opinion on an approach I've tried.

I managed to execute the script and retrieve the value using the following method:
```
let promise_global = runtime.execute_script("<user-script>", FastString::Owned(Box::from(script_with_params)))?;
runtime.run_event_loop(PollEventLoopOptions::default()).await?;
let scope = &mut runtime.handle_scope();
let result_global = v8::Local::new(scope, promise_global);
let promise = unsafe { v8::Local::<v8::Promise>::cast(result_global) }; // use unsafe
let result = promise.result(scope).to_rust_string_lossy(scope);
```
This method seems to work for executing the script and retrieving the value. However, I am wondering if there is an even better or more efficient way to achieve this. Particularly, I'm interested in understanding if there's a way to optimize the handling of promises and the extraction of their results.

Any further insights or suggestions you could provide would be greatly appreciated.

Thank you once again for your assistance.

**Comment by bartlomieju** [comment]
> Particularly, I'm interested in understanding if there's a way to optimize the handling of promises and the extraction of their results.

There's not much that can be done here - you pretty much used the canonical way that V8 exposes. Instead of using `cast` that requires `unsafe` you can use `try_from` instead.

**Comment by huiali** [comment]
Thanks!
