### ISSUE TITLE
Error in debug if platform is never initialized on main thread?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_core#423]
It might be useful to error in debug if the platform is never initialized on the main thread. This will help prevent situations where someone initializes v8 on separate threads without doing it on the main thread once (as in my case https://github.com/dprint/dprint-plugin-prettier/pull/74).

**Comment by bartlomieju** [comment]
I think it makes sense, the question is if we should just print a message, panic or use `new_default_unprotected_platform` in this case.

The code to check if we're on main thread is:
```rust
if thread::current().id() == thread::main().id() {
        println!("Currently on the main thread");
    }
```

**Comment by bartlomieju** [comment]
Related https://github.com/denoland/deno_core/issues/217 - maybe we should always use "unprotected" platform with `#[cfg(test)]`?

**Comment by bartlomieju** [comment]
Appears this was addressed in https://github.com/denoland/deno_core/commit/ec8cbe2f15d52acca4b6d4db687a77966bdb184d.
