### ISSUE TITLE
Enhancement Request: Shared `JsRuntime` State Across Threads

### ISSUE THREAD

**Issue by huiali** [denoland/deno_core#462]
Hello,

I am currently working on a project where I extensively use Deno's `JsRuntime`. I've encountered a scenario where I need to share the `JsRuntime` state across different threads without having to create a new instance for each operation. This has become a concern, especially considering the potential increase in resource consumption, as a new `JsRuntime` instance is created for each incoming message or request.

To optimize resource usage and performance, I am looking for a way to share a single `JsRuntime` instance across multiple threads. I tried using `lazy_static` to create a global `JS_RUNTIME` instance. However, due to `JsRuntime`'s internal use of `Rc`, it does not satisfy the `Send` trait, thus preventing it from being shared across threads safely.

1. Is there an existing pattern or recommended practice for sharing `JsRuntime` state across threads within the current Deno architecture?

2. Would it be feasible to consider an enhancement that allows for a more straightforward way to create and share a global `JsRuntime` instance (or its equivalent state) across threads?

I believe such a feature would greatly benefit applications that require extensive and efficient use of JavaScript execution environments, particularly in multi-threaded contexts.

Thank you for your time and consideration.

**Comment by huiali** [comment]
I have restructured the implementation using MPSC (Multiple Producer, Single Consumer), and I am closing this issue.

**Comment by meskill** [comment]
Hey, @huiali 

I'm encountering similar problem with deno_core and I'm trying to optimize JsRuntime usage across many threads. 

Can you share the details of the solution you've implemented? I've also tried to share JsRuntime by putting it to separate thread and communicate with it through mpsc channel, but most of the useful functions of it requires JsRuntime to be mutable reference and that is not quite scalable for concurrent execution.

**Comment by bartlomieju** [comment]
You can see how Deno does it itself - here's the code that runs a TS compiler on a separate thread and uses channels to communicate the results: https://github.com/denoland/deno/blob/6c6e49629c216f2b2a8d90ed2d590c0f727f62a4/cli/lsp/tsc.rs#L4078-L4146

**Comment by meskill** [comment]
> You can see how Deno does it itself - here's the code that runs a TS compiler on a separate thread and uses channels to communicate the results: https://github.com/denoland/deno/blob/6c6e49629c216f2b2a8d90ed2d590c0f727f62a4/cli/lsp/tsc.rs#L4078-L4146

Thanks, it helped.
I'm using this code now

```rust
loop {
            tokio::select! {
                biased;
                Some((send_response, request)) = receiver.recv() => {
                    has_tasks = true;
                    self.handle(request, send_response, tx.clone()).unwrap();
                },
                Some((send, value)) = rx.recv() => {
                    let mut handle = self.js_runtime.handle_scope();
                    let value = Local::new(&mut handle, value);
                    let message: Message = serde_v8::from_v8(&mut handle, value).unwrap();

                    let _ = send.send(message);
                },
                _ = self.js_runtime.run_event_loop(PollEventLoopOptions::default()), if has_tasks => {
                    has_tasks = false;
                }
            }
        }
```
