### ISSUE TITLE
deno_console cannot be conviently used with deno_core due to type export/extension!() macro return type issue

### ISSUE THREAD

**Issue by kairoswater-jason** [denoland/deno_core#560]
Encountered this when attempting to use the deno_console extension as it was intended to be used rather than having to go through the shenanigans that Rustyscript had to go through to register the deno_console extension.

The extension!() macro generates functions that return type deno_core::extensions::Extension, but the crate requires users to use deno_core::Extension (a renamed version of deno_core::extensions::Extension which gets treated as a distinct type). When the extension!() macro is executed in the deno_console crate it seems to fail to generate the correct return types.

This makes it impossible to make use of the deno_console crate's function to generate the deno_console extension `deno_console::deno_console::init_ops_and_esm()`

It may be a simple oversight regarding exporting/renaming of internal library types.

> error[E0308]: mismatched types
>    --> src/main.rs:236:37
>     |
> 236 |         extensions: vec![ext_codec, deno_console::deno_console::init_ops_and_esm()],
>     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `deno_core::Extension`, found `deno_core::extensions::Extension`
>     |
>     = note: `deno_core::extensions::Extension` and `deno_core::Extension` have similar names, but are actually distinct types
> note: `deno_core::extensions::Extension` is defined in crate `deno_core`
>    --> /home/jason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.256.0/extensions.rs:493:1
>     |
> 493 | pub struct Extension {
>     | ^^^^^^^^^^^^^^^^^^^^
> note: `deno_core::Extension` is defined in crate `deno_core`
>    --> /home/jason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.258.0/extensions.rs:544:1
>     |
> 544 | pub struct Extension {
>     | ^^^^^^^^^^^^^^^^^^^^
>     = note: perhaps two different versions of crate `deno_core` are being used?
> 

cargo.toml
```
[dependencies]
deno_core = "0.258.0"
deno_console = "0.136.0"
```

main.rs
```
use deno_core::*;
...
// Initialize a runtime instance
let mut runtime = JsRuntime::new(RuntimeOptions {
    extensions: vec![ deno_console::deno_console::init_ops_and_esm()],
    ..Default::default()
});
```

Unrelated side question: Is it really nessesary to do everything that Rustyscript did ([in its console and rustyscript extensions](https://github.com/rscarson/rustyscript/tree/0fd168e3b82106c3c4551f1e744b113e26f2b109/src/ext)) just to register the console extension?

**Comment by 0f-0b** [comment]
The compiler points out that “two different versions of crate `deno_core` are being used” – `deno_console` 0.136.0 [depends on `deno_core` 0.256.0](https://docs.rs/crate/deno_console/0.136.0/source/Cargo.toml), while you are using `deno_core` 0.258.0.

**Comment by bartlomieju** [comment]
FYI There will be another release of Deno tomorrow that will use the latest `deno_core` release.
