### ISSUE TITLE
Move `op_is_terminal` to deno_core

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno_core#580]
This op exists in deno_runtime, but it's more suitable for deno_core.

**Comment by muddlebee** [comment]
can I work on this :eyes: ? might be a good starting point to get familiar with the codebase and ops

**Comment by bartlomieju** [comment]
Sure, it's up for grabs.

**Comment by nathanwhit** [comment]
Done in https://github.com/denoland/deno_core/pull/638.
