### ISSUE TITLE
Creating a new `JsRuntime` leaks memory via `Box::leak`

### ISSUE THREAD

**Issue by svix-aaron1011** [denoland/deno_core#594]
Each time a new `JsRuntime` is created, a `v8::ExternalReferences` gets leaked: https://github.com/denoland/deno_core/blob/4b38e2b920d5844a556c853d722bfb82bd3b5562/core/runtime/bindings.rs#L110

This can be a problem in applications that create a new `JsRuntime` to handle incoming requests

**Comment by mmastrac** [comment]
Ah yeah. We need to keep the externalrefs in `IsolateAllocations` rather than leaking each time. The lifetime of these refs just needs to be > than the isolate itself and the `IsolateAllocations` struct should be a good place to keep the allocation to drop after the fact.

**Comment by bartlomieju** [comment]
This was fixed in https://github.com/denoland/deno_core/pull/632.
