### ISSUE TITLE
core.read(stdin, buf) blocks program from exiting even when the promise is unref'd

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_core#648]
If I unref'd the `op_read` promise for Deno.stdin.rid, I expect that promise doesn't block the program from exiting, but it still prevents the program from exiting until any inputs are given from the terminal.

For example, I expect the below program exits immediately after printing `1`, but it actually waits for any input given from the terminal before exiting (If I give inputs to the program, it still exits without printing `2`. So it seems `unrefOpPromise` works somehow, and there seems something else blocking the program from exiting).

```js
const { core } = Deno[Deno.internal];
const opPromise = core.read(Deno.stdin.rid, new Uint8Array(10));
core.unrefOpPromise(opPromise);

async function main() {
  console.log(1);
  await opPromise;
  console.log(2);
}

main();
```

related: https://github.com/denoland/deno/issues/21796 (The above issue seems blocking fixing this issue)

**Comment by mmastrac** [comment]
This definitely looks like a bug. We should only block the event loop when there's a unref'd promise being explicit awaited.
