### ISSUE TITLE
`OpCtx` leaks `CFunctionInfo`

### ISSUE THREAD

**Issue by svix-aaron1011** [denoland/deno_core#649]
When creating a new `JsRuntime`, a `CFunctionInfo` gets allocated: https://github.com/denoland/deno_core/blob/ddbffc518114f862d94c99a4821c647f6aa0ed0d/core/ops.rs#L115-L123

However, it isn't freed when `OpCtx` is dropped, leading to a memory leak

**Comment by bartlomieju** [comment]
@mmastrac can we store it in `IsolateAllocations`?

**Comment by mmastrac** [comment]
I think we just need to free it in Drop
