### ISSUE TITLE
[Feat] Can executing 'Deno. cwd()' in the worker return an independent directory?

### ISSUE THREAD

**Issue by hanrea** [denoland/deno_core#794]
I prefer an independent environment for executing workers. I currently treat workers as a lightweight container and hope that each worker has their own directory to handle certain tasks in conjunction with Deno's permission management.

**Comment by bartlomieju** [comment]
`Deno.cwd()` is only available in `deno`, not `deno_core`. That said - `Deno.cwd()` returns the CWD based on a syscall, so if you have multiple `JsRuntime` instance in a single process they will all return the same CWD.

**Comment by hanrea** [comment]
thanks！
