### ISSUE TITLE
Feature request: Removal or overwriting of builtin-ops

### ISSUE THREAD

**Issue by rscarson** [denoland/deno_core#836]
In [this function](https://github.com/denoland/deno_core/blob/665a61d733d4c9cb18aa81c050c135b51e9b51f5/core/extension_set.rs#L99), ops are verified to be unique

Due to this there is no possible way to disable builtin ops that may be harmful in some cases, such as `op_panic`, which blows up the thread containing the runtime.

Could this check be made optional, or could a method of removing ops be added? op_panic is causing a major headache for my crate, due to the denial-of-service vulnerability it causes

I can't even easily stub it out, since snapshots reset the ops list

**Comment by bartlomieju** [comment]
You can disable an op like this: https://github.com/denoland/deno_core/blob/665a61d733d4c9cb18aa81c050c135b51e9b51f5/core/examples/disable_ops.rs#L12

Or override its implementation like this:
https://github.com/denoland/deno/blob/994b6327d3af5721fa4fcf6fbfe856a6f6da79cf/runtime/ops/os/mod.rs#L69-L73

**Comment by rscarson** [comment]
well shit! Thanks!
