### ISSUE TITLE
Creating a `JsRuntime` leaks memory with deno_core 0.307.0

### ISSUE THREAD

**Issue by svix-aaron1011** [denoland/deno_core#894]
The following program:

```rust
fn main() {
    loop {
        deno_core::JsRuntime::new(deno_core::RuntimeOptions::default());
    }
}
```

leaks several megabytes of memory per second on my machine (even though each `JsRuntime` is immediately dropped).
Running the program under Heaptrack, it looks like the `RawHeap` transitively created by `create_cpp_heap` is never deallocated

**Comment by devsnek** [comment]
Fix: https://chromium-review.googlesource.com/c/v8/v8/+/5837978
