### ISSUE TITLE
A question about code generating by `core/rebuild_async_stubs.js`

### ISSUE THREAD

**Issue by Hajime-san** [denoland/deno_core#917]
When I tried to locally implement an op function with 14 arguments in `deno/ext`, and the build failed due to the argument limit imposed by `core/rebuild_async_stubs.js`.
Looking at the contents of `core/rebuild_async_stubs.js`, it looks like the function is defined each time depending on the number of arguments.
Is there a reason why this can't be replaced by using rest parameters (`...theArgs`) as shown below?

```js
function setUpAsyncStub(opName, originalOp) {
  const fn = function async_op(...theArgs) {
    const id = nextPromiseId;
    try {
      const maybeResult = originalOp(id, ...theArgs);
      if (maybeResult !== undefined) {
        return PromiseResolve(maybeResult);
      }
    } catch (err) {
      ErrorCaptureStackTrace(err, async_op);
      return PromiseReject(err);
    }
    if (isLeakTracingEnabled) {
      submitLeakTrace(id);
    }
    nextPromiseId = (id + 1) & 0xffffffff;
    return setPromise(id);
  };

  ObjectDefineProperty(fn, "name", {
    value: opName,
    configurable: false,
    writable: false,
  });
  return fn;
}
```

https://github.com/denoland/deno_core/blob/7258aa325368a8e2c1271a25c1b4d537ed41e9c5/core/00_infra.js#L193-L236

**Comment by bartlomieju** [comment]
We benchmarked it and using rest argument was way slower.

As a side note: using 14 arguments might not be the best idea. Consider using and array to "group" some arguments together.

**Comment by Hajime-san** [comment]
Thanks to you I have resolved my doubts!

> Consider using and array to "group" some arguments together.

Good to hear. I will use it as a reference.👀
