### ISSUE TITLE
Doesn't build on docs.rs anymore

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_core#98]
https://docs.rs/crate/deno_core/0.197.0/builds/870081

**Comment by andreubotella** [comment]
It's interesting that `deno_ops` [does build](https://docs.rs/deno_ops/latest/deno_ops/) on docs.rs. Could this be because the release script does `cargo update` on `deno_core` before `deno_ops`, when the latter is a dependency of the former?

**Comment by mmastrac** [comment]
This is very strange:

```
[INFO] [stderr]  Documenting deno_core v0.197.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0463]: can't find crate for `deno_ops`
```

Maybe it's a release timing issue? The crate is definitely pushed now, but I am curious if there was a period where it wasn't available.

**Comment by mmastrac** [comment]
This is a real puzzler. Filed upstream as I think it might be a build glitch over there: https://github.com/rust-lang/docs.rs/issues/2178

**Comment by andreubotella** [comment]
I think the build happens as the crate is uploaded, not afterwards, and it seems like the release script uploads crates in the order in which they're listed on the workspace root `Cargo.toml`, which has `core` before `ops`.
